name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Build Backend
      - name: Build backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build

      # 4. Build Frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          tsc --noEmit --skipLibCheck
          npm run build

      # 5. Deploy Backend to Railway (using Railway CLI)
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy backend to Railway
        working-directory: ./backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --detach --service ${{ secrets.RAILWAY_SERVICE_ID }}

      # 6. Deploy Frontend to Vercel
      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod'

      # 7. Notify success
      - name: Deployment successful
        run: echo "✅ Backend deployed to Railway & Frontend deployed to Vercel"