name: Docker Compose Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        cat > .env << EOF
        NODE_ENV=production
        MONGODB_URI=mongodb://admin:password123@mongodb:27017/taskmanager?authSource=admin
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
        JWT_ACCESS_EXPIRY=15m
        JWT_REFRESH_EXPIRY=7d
        BCRYPT_SALT_ROUNDS=12
        ALLOWED_ORIGINS=http://localhost:3000
        VITE_API_BASE_URL=http://localhost:5000/api
        EOF

    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d

    - name: Wait for services to be healthy
      run: |
        timeout 300 bash -c 'until docker-compose ps | grep -q "healthy"; do sleep 5; done'

    - name: Run health checks
      run: |
        curl -f http://localhost:5000/api/health || exit 1
        curl -f http://localhost:3000/health || exit 1

    - name: Cleanup on failure
      if: failure()
      run: docker-compose down
